### ISSUE TITLE
How to resolve import modules from tsconfig `baseUrl`

### ISSUE THREAD

**Issue by gerardolima** [garthk/lab-transform-typescript#7]
While I can compile my project with `tsc`, I receive errors like `Error requiring file: ...` for files actually used in the compilation process. Is any extra configuration needed for these situations?

**Comment by Gakura** [comment]
I've just encountered the same issue. My `tsconfig.json` contains `"baseUrl": "./src"` so my solution was to set the env `NODE_PATH=./src` .

Test script in my package.json:
`"test:database": "NODE_PATH=./src env-cmd -e development,test lab --sourcemaps --transform node_modules/lab-transform-typescript --colors src/libs/database --timeout 10000",`

**Comment by gerardolima** [comment]
closed due to no-response
